### ISSUE TITLE
Unexpected 62% file size increase

### ISSUE THREAD

**Issue by Callumro** [joeShuff/tdarr-plugins#1]
Hey, first of all thanks for this. It has solved an issued with my plex server which was unable to keep up with transcoding for 1080p h264 (high level 10) files to my nvidia shield, and the current community plugins didn't really have a solution to drop the profile from high to something lower.

Currently this is working just fine and I am able to steam without transcoding after using your plugin but I wanted to call out this rather significant file size increase. It may very well be that I just don't understand enough about codecs and this is normal?

File original - 854.1 MB (Version 1):
https://pastebin.com/GtQGtv33

File after Tdarr_Plugin_JoeCustomVideo - 1.358 GB (Version 2):
https://pastebin.com/1jUQ3WJk

Any thoughts on why there is an increase in file size? I would have expected the same or smaller after running the conversion.

**Comment by joeShuff** [comment]
Hiya, sorry that you're having trouble with this. It's not something I've noticed myself but I haven't paid attention to file sizes.

It is possible that the lower profile leads to this file size change but the priority for me was to watch without transcoding not a file size so I didn't confirm.

Have you ran a transcode with just this plugin and no more to make sure this is the culprit?

**Comment by Callumro** [comment]
I had previously run the Tdarr_Plugin_z2ab_TheRealShadoh_FFmpeg_Subs_H264_Slow plugin on the same file, running yours seems to increase the file size, then I can reduce it again if I run the Shadoh plugin on the same file.

I thought I would bring it to your attention, its not stopping me from using your plugin but it seemed strange. It very well has something to do with switching between .mkv and .mp4 but I don't know enough to say for sure. I am happy to leave it at that to be honest haha

**Comment by joeShuff** [comment]
If you want to change the mkv to mp4 you can edit the file yourself, look for mkv and change it, should be simple enough! Feel free to double check your changes with me to be safe! Just MKV works for my use case but I understand its not the same for everyone :)
