### ISSUE TITLE
Files remaining in hevc?

### ISSUE THREAD

**Issue by cjnunn88** [joeShuff/tdarr-plugins#2]
For whatever reason my files are staying in hevc instead of changing to h264. 

JSON requested
[data.txt](https://github.com/joeShuff/tdarr-plugins/files/12304113/data.txt)

Plugin stack: 
EDIT: I previously also had the "New File Size Check" plugin at the bottom of the stack, but I removed it after it caused a failure when using a different video plugin.
![image](https://github.com/joeShuff/tdarr-plugins/assets/141849485/edaf7845-bcc9-4935-ba02-a05bbc6e8b28)

Current plugin stack: 
![image](https://github.com/joeShuff/tdarr-plugins/assets/141849485/3bab700a-5e51-437b-9daa-71fe5421a543)

**Comment by joeShuff** [comment]
from a quick look at the ffprobe data, it should be transcoding. `"codec_name": "hevc"` should be passing. I'd like to see the trace of the transcode. To get it do the following.

In the "Transcode Success" or "Transcode Error" tables (wherever this file has gone to), find the file row. Then click on "Report" at the end
![image](https://github.com/joeShuff/tdarr-plugins/assets/15524362/abe5e429-6758-444e-8d18-70aaa7b19613)

Then in the report click the download button at the top
![image](https://github.com/joeShuff/tdarr-plugins/assets/15524362/bd8a1917-5773-48f1-b0f2-aa5f13cad0d6)
 

Then please send over that file, that'll show me the log for that transcode run and I can hopefully see whats going on.

**Comment by cjnunn88** [comment]
Sure thing. As soon as this is finished in a couple hours, I'll upload that. I had already wiped out all of the old stuff.

**Comment by cjnunn88** [comment]
Out of curiosity, is it possible to set up separate libraries for the same source location so that I could have one library that only processes audio, and the other that only processes video, so theoretically, I could have 2 jobs running on the same file at the same time: one transcoding audio, and the other transcoding video?

**Comment by joeShuff** [comment]
> Sure thing. As soon as this is finished in a couple hours, I'll upload that. I had already wiped out all of the old stuff.

Sounds good!

> Out of curiosity, is it possible to set up separate libraries for the same source location so that I could have one library that only processes audio, and the other that only processes video, so theoretically, I could have 2 jobs running on the same file at the same time: one transcoding audio, and the other transcoding video?

I think technically you _can_ but you shouldn't. Tdarr uses caches, so if they're running at the same time, whichever one finishes last will be the final file.

Both start transcoding -> Library A finishes and copies "cache" file to new destination. -> Library B was mid transcoding that file so worst case, transcode will immediately fail, best case, Library B will complete then copy its cache and overwrite what Library A did. So no, don't have multiple libraries for the same files. Here is my stack for your reference.

![image](https://github.com/joeShuff/tdarr-plugins/assets/15524362/8eceecd1-dda9-4ae5-b997-9f6fb06b45c3)

**Comment by cjnunn88** [comment]
Ah...makes sense.

**Comment by cjnunn88** [comment]
Ok...I apologize. I can only assume that the "New File Size Check" was throwing out the new file, or one of the other plugins did something weird. It does seem to be in h264 now, however Plex is still having to transcode it, but that's probably the audio. 

Does your audio plugin only look for specific audio codecs? or does it make them all the specified audio codec?

**Comment by joeShuff** [comment]
Ay glad to hear it worked alright. My audio plugin converts all audio tracks to the desired codec.

You should be able to see a reason that plex is transcoding. I use Jellyfin myself and I know that provides a reason for transcode.

I use aac for my audio preference.

**Comment by cjnunn88** [comment]
Playing from my iPhone (just because it's right next to me):
![image](https://github.com/joeShuff/tdarr-plugins/assets/141849485/d2586b21-e5b1-4ee2-8720-e6dfd5a9a014)

Playing from my Xbox (usual device):
![image](https://github.com/joeShuff/tdarr-plugins/assets/141849485/727720ed-4825-46db-a8e9-f2ec12d3d1fb)

Could it be that it has VOBSUB subtitles?

**Comment by cjnunn88** [comment]
![image](https://github.com/joeShuff/tdarr-plugins/assets/141849485/0a829922-b654-4cc8-9845-9b36f3f2efeb)
That must have been it. Sorry I wasted your time. I think this is finally going to work though.

New Stack: 
![image](https://github.com/joeShuff/tdarr-plugins/assets/141849485/fbce8533-f027-4487-87d1-fc8231239677)

Does your Audio plugin convert them to AAC stereo? or just AAC with the same channel count? The one I'm currently using actually adds a new AAC Stereo track, but then I have the other plugin that only keeps one track so it removes anything that isn't AAC stereo. If yours converts the track without adding a new one, then I might go with yours. However, I may still keep the other one in there, because I don't want anything that isn't English AAC stereo. 

I wish there was an easy way to extract VOBSUB to SRT, but I'll have Bazarr for getting the subtitles, so I'm not that worried about it. It would just be nice to keep the embedded subtitles since they are already synced.

**Comment by joeShuff** [comment]
Glad you got it working in the end, you didn't waste any time don't worry. Glad I could help even if it was being a rubber duck!

I believe my audio one will convert all audio tracks to AAC and keep the channel count, tbh I'm not sure. This is the argument it provides if you wanna google it
`-map 0:a -c:a ${encoder}`

I removed all subtitle stuff from my stack because like you said, I didn't like removing the streams when they are already synced. I just changed my Jellyfin to not serve up those tracks right now to avoid transcoding.

**Comment by joeShuff** [comment]
It might be worth noting that I've just pushed an update to my plugin to contain some other video filters that I found I needed a few months ago. 

These plugins are definitely a "make a change when I need it" situation so it might not apply to you but it definitely got some files for me to stop transcoding.

**Comment by cjnunn88** [comment]
Cool. I'll check it out and see if it's something I need. I really just needed something that would properly convert it from 265 to 264, and this is now doing that for me.

**Comment by cjnunn88** [comment]
One more question. 

I'm trying to set up a remote node on my laptop that has an NVIDIA GPU, but it's using the CPU instead of the GPU. Is there something I need to set up for it to use the GPU instead? or does it detect the hardware from the server itself?

EDIT: Never mind. I think I figured it out. 
![image](https://github.com/joeShuff/tdarr-plugins/assets/141849485/66f0a940-feb7-404e-be49-ee5f356c4046)

**Comment by joeShuff** [comment]
Yep you figured it out correctly. The command that needs issuing is slightly different for GPUs and this dropdown was the only way I could determine whether it supported GPU or not. Don't think its the _correct_ way of doing that, but it does the job.

**Comment by cjnunn88** [comment]
UPDATE: Using my laptop as a node has been a godsend. In the future, I plan on building out a server, but for now, this is going to do the trick nicely. 

When I was using the mini pc for transcoding, the files were taking FOREVER to transcode (i mean, since my last post, it was transcoding only "Heroes" and didn't even finish that), and the files were actually getting larger. After switching to my laptop yesterday afternoon, it's transcoded almost 90 files, and the files are significantly smaller. over 80GB saved and counting.
![image](https://github.com/joeShuff/tdarr-plugins/assets/141849485/d8eb556d-d5c8-45f9-bab3-721916bf97a7)
![image](https://github.com/joeShuff/tdarr-plugins/assets/141849485/c1fff80f-a2ca-429b-9524-2127b420d9ee)

**Comment by joeShuff** [comment]
Good to hear!
